:py:mod:`CodonU.cua_errors.codon_table_exist_err`
=================================================

.. py:module:: CodonU.cua_errors.codon_table_exist_err


Module Contents
---------------

.. py:exception:: CodonTableExistsError(code, val)

   Bases: :py:obj:`CodonU.cua_errors.codon_usage_err.CodonUsageError`

   Occurs when id, name or alt_name of a new table is same with existing tables


